[server]
host: 0.0.0.0
port: 7125
max_upload_size: 1024 # The maximum size allowed for a file upload (in MiB).  Default 1024 MiB
klippy_uds_address: ~/printer_data/comms/klippy.sock # Path to klippy Unix Domain Socket

# Post processing for object cancel.
# Not recommended for low resource SBCs such as a Pi Zero. Default False
[file_manager]
enable_object_processing: True

[authorization]
cors_domains:
    https://my.mainsail.xyz
    http://my.mainsail.xyz
    http://*.local
    http://*.lan
trusted_clients:
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128
    127.0.0.1
    
[octoprint_compat] # enables partial support of Octoprint API

[history] # enables moonraker to track and store print history.

[announcements] # this enables moonraker announcements for mainsail
subscriptions:
    mainsail
    
[update_manager] # this enables moonraker's update manager
refresh_interval: 168
enable_auto_refresh: True

[update_manager crowsnest] # this enables crownest's update
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
managed_services: crowsnest
install_script: tools/pkglist.sh

[update_manager sonar] # Sonar update_manager entry
type: git_repo
path: ~/sonar
origin: https://github.com/mainsail-crew/sonar.git
primary_branch: main
managed_services: sonar
system_dependencies: resources/system-dependencies.json

[update_manager Klipper-Adaptive-Meshing-Purging]
type: git_repo
channel: dev
path: ~/Klipper-Adaptive-Meshing-Purging
origin: https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
managed_services: klipper
primary_branch: main

[update_manager KlipperScreen]
type: git_repo
path: ~/KlipperScreen
origin: https://github.com/KlipperScreen/KlipperScreen.git
virtualenv: ~/.KlipperScreen-env
requirements: scripts/KlipperScreen-requirements.txt
system_dependencies: scripts/system-dependencies.json
managed_services: KlipperScreen
